title: Kasia & Pawel sweet web!
author: GitHub User - Papi
email: mysecretmail@unknowndomain.com
description: > # this means to ignore newlines until "baseurl:"
  This website is totally awesome :) Check out our content you won't believe
  how wonderful it is.

# social links
twitter_username: papi-twitter-handle
github_username:  papi-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
